# Generated by Django 3.0 on 2019-12-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Introduce Placa', max_length=20)),
                ('ultima_pos_lat', models.DecimalField(decimal_places=7, help_text='Introduce Última latitud', max_digits=11)),
                ('ultima_pos_long', models.DecimalField(decimal_places=7, help_text='Introduce Última longitud', max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
